# This file lists the dependencies needed to build and test all of the package.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: darmonpoints-dev
channels:
  - conda-forge
dependencies:
  - black>=23,<24
  - isort
  - ipywidgets
  - jupytext
  - myst-parser
  - myst-nb
  - pip
  - pylint>=3,<3.1
  - python
  - sagelib
  - sphinx
  - pip:
    - linkchecker
    - sphinx_rtd_theme
    - sphinx-design
